services:
  - type: web
    name: nically
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    region: oregon
    plan: free
    runtime: python
